name = "dagraba-studio"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages build output (required for Pages)
pages_build_output_dir = ".open-next"
main = ".open-next/worker.js"
